### ISSUE TITLE
Reset Autoplay

### ISSUE THREAD

**Issue by priorwalter** [gbbr/UberAccordion#1]
I'm wondering if there is a method to reset the autoplay after a pane has been opened manually.  I'm using your script for a project and I was hoping I could get some help on this functionality.  If you'd like, I'd be willing to donate to you for some help on this.

Thanks,
Prior.

**Comment by gbbr** [comment]
Thanks for reporting this issue. I'm not sure what you mean by Reset. Currently, if you click on a slide while Autoplay is on, autoplay should stop. Is this not the behaviour you desire?

**Comment by gbbr** [comment]
Also, it is worth nothing that you have full control of the autoplay feature via `setAutoplay`. Example:

``` javascript
var uberAccordion = $('.accordionContainer').uberAccordion({
     // ... options here
});

//....

uberAccordion.setAutoplay(true); // reset autoplay
```

One option would be to listen for the header clicks and just resume afterwards if this is what you're after.
